version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  backend:
    image: aniket5180/my_project:backend
    container_name: backend_app
    ports:
      - "3000:3000"
    networks:
      - app-network
    
  frontend:
    image: aniket5180/my_project:frontend
    container_name: frontend_app
    ports:
      - "8000:80"
    networks:
      - app-network
    depends_on:
      - backend